networks:
  internal:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    networks:
      - internal
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file: .env
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - frontend
    volumes:
      - ./logs:/app/logs
    networks:
      - internal
    environment:
      - GUNICORN_WORKERS=2
      - GUNICORN_TIMEOUT=360
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    networks:
      - internal